# Workflow name
name: 'Docsite publish to Github Pages'

on:
  push:
    branches:
      - chore/ghp-deployments-test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_id: ${{ steps.artifact_upload.outputs.artifact_id }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      # - name: Install Playwright Browsers
      #   run: yarn playwright install --with-deps
      #
      #
      - name: Affected Deployable Storybooks
        id: affected_storybooks_count
        run: |
          affected_count=$(yarn --silent nx show projects -t build-storybook:docsite --affected --verbose false | wc -l | tr -d ' ')
          echo "value=$affected_count" >> $GITHUB_OUTPUT

      - name: Build affected storybooks
        if: steps.affected_storybooks_count.outputs.value > 0
        run: |
          yarn nx run-many -t build-storybook:docsite --nxBail

      - name: Upload Pages Artifact
        if: steps.affected_storybooks_count.outputs.value > 0
        id: artifact_upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: './apps/public-docsite-v9/dist/'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.artifact_id
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
