# Workflow name
name: 'Docsite publish to Github Pages'

on:
  push:
    branches:
      - chore/ghp-deployments
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    # if: ${{ github.repository_owner == 'microsoft' }} && ${{ contains(github.event.head_commit.message, 'applying package updates') || github.event_name == 'workflow_dispatch' }}

    # outputs:
    # status: ${{ steps.verify-react-components-changed.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@v4
        name: Checkout [master]

      - name: Verify react-compoenents has changed
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
        id: verify-react-components-changed
        with:
          files: |
            packages/react-components/react-components/package.json
  build:
    runs-on: ubuntu-latest
    # needs: check
    # if: needs.check.outputs.status == 'true'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Build storybook
        run: |
          yarn nx run public-docsite-v9:build-storybook --nxBail
          yarn nx run public-docsite-v9:build-storybook:react --nxBail
        env:
          STORYBOOK_APPINSIGHTS_INSTRUMENTATION_KEY: ${{ secrets.STORYBOOK_APPINSIGHTS_INSTRUMENTATION_KEY }}

      - name: Build Charts Storybook
        run: |
          yarn nx run chart-docsite:build-storybook --nxBail
        env:
          STORYBOOK_BASE: '/fluentui/charts/'

      - name: Stage site for Pages (root + /react + /charts)
        run: |
          rm -rf _site
          mkdir -p _site/react _site/charts
          cp -R apps/public-docsite-v9/dist/storybook/* _site/
          cp -R apps/public-docsite-v9/dist/react/* _site/react/
          cp -R apps/chart-docsite/dist/storybook/* _site/charts/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
